// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RestorDbContext))]
    [Migration("20260601141839_madeCascadDelete")]
    partial class madeCascadDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domains.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("CompanyId");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e5a4001-2b5d-08dc-0000-000000000000"),
                            Address = "avenue",
                            Country = "USA",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = new Guid("8e5a4002-2b5d-08dc-0000-000000000000"),
                            Address = "Moscow",
                            Country = "Russia",
                            Name = "Google"
                        },
                        new
                        {
                            Id = new Guid("8e5a4003-2b5d-08dc-0000-000000000000"),
                            Address = "Leningradka",
                            Country = "Germany",
                            Name = "Telegram"
                        });
                });

            modelBuilder.Entity("Domains.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d0bb8001-ea50-08dc-0000-000000000000"),
                            Age = 13,
                            CompanyId = new Guid("8e5a4001-2b5d-08dc-0000-000000000000"),
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("d0bb8002-ea50-08dc-0000-000000000000"),
                            Age = 75,
                            CompanyId = new Guid("8e5a4002-2b5d-08dc-0000-000000000000"),
                            Name = "George"
                        },
                        new
                        {
                            Id = new Guid("d0bb8003-ea50-08dc-0000-000000000000"),
                            Age = 130,
                            CompanyId = new Guid("8e5a4003-2b5d-08dc-0000-000000000000"),
                            Name = "Mishal"
                        });
                });

            modelBuilder.Entity("Domains.Employee", b =>
                {
                    b.HasOne("Domains.Company", "Company")
                        .WithMany("Employees")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Domains.Company", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
